language: node_js

env:
  - CXX=g++-5

sudo: required

node_js:
  - "6"

before_install:
  - npm install -g node-gyp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

install: true

services: mongodb

notifications:
  slack:
    rooms:
      - biketrack:g1LUdyTlNsIF2282uVHhBIsx#api
